apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-hello
  namespace: "vk8s_namespace"
  annotations:
    ves.io/virtual-sites: shared/agility-k8s-vsite
    ves.io/workload-flavor-nginx: tiny
spec:
  selector:
    matchLabels:
      app: nginx-hello
  replicas: 1
  template: 
    metadata:
      labels:
        app: nginx-hello
    spec:
      containers:
      - name: nginx
        image: nginxdemos/hello
        ports:
          - name: nginx-hello
            containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-hello
  namespace: "vk8s_namespace"
spec:
  type: ClusterIP
  selector:
    app: nginx-hello
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80